In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('dataset/credit-a.csv', header=None)

In [4]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0,30.83,0.000,0,0,9,0,1.25,0,0,1,1,0,202,0.0,-1
1,1,58.67,4.460,0,0,8,1,3.04,0,0,6,1,0,43,560.0,-1
2,1,24.50,0.500,0,0,8,1,1.50,0,1,0,1,0,280,824.0,-1
3,0,27.83,1.540,0,0,9,0,3.75,0,0,5,0,0,100,3.0,-1
4,0,20.17,5.625,0,0,9,0,1.71,0,1,0,1,2,120,0.0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,0,21.08,10.085,1,1,11,1,1.25,1,1,0,1,0,260,0.0,1
649,1,22.67,0.750,0,0,0,0,2.00,1,0,2,0,0,200,394.0,1
650,1,25.25,13.500,1,1,13,7,2.00,1,0,1,0,0,200,1.0,1
651,0,17.92,0.205,0,0,12,0,0.04,1,1,0,1,0,280,750.0,1
652,0,35.00,3.375,0,0,0,1,8.29,1,1,0,0,0,0,0.0,1

In [5]:
x_values = data.iloc[:, :-1] #取所有行所有列
y_values = data.iloc[:, -1].replace(-1,0)  #取所有行，最后一列

In [8]:
X = torch.from_numpy(x_values.values).type(torch.float32)
Y = torch.from_numpy(y_values.values.reshape(-1, 1)).type(torch.float32)

In [9]:
from torch import nn

In [10]:
#创建模型
model = nn.Sequential(
        nn.Linear(15,1), #输入15个属性，输出1个属性
        nn.Sigmoid() #激活层，使所有层顺序连接
)

In [11]:
model

Sequential(
  (0): Linear(in_features=15, out_features=1, bias=True)
  (1): Sigmoid()
)

In [12]:
loss_fn = nn.BCELoss() #二元交叉熵损失
opt = torch.optim.Adam(model.parameters(), lr=0.001)
batches = 16  #16个数据为一组
number_of_batch = 653//16 #全部数据训练一次需要多少组
epoches = 1000 #循环1000次

for epoch in range(epoches):
    for i in range(number_of_batch):
        start = i*batches
        end = start + batches
        x = X[start:end]
        y = Y[start:end]
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        opt.zero_grad()
        loss.backward()
        opt.step()

In [13]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[-3.0026e-01, -8.9373e-03,  3.5768e-02,  2.7464e-01,  2.6797e-01,
                       -5.5486e-03,  2.0725e-01, -1.5519e-01,  4.4834e+00,  3.1429e-01,
                       -1.4420e-01, -2.8711e-01, -2.2624e-01,  2.0073e-03,  1.1243e-04]])),
             ('0.bias', tensor([-0.4971]))])

In [15]:
((model(X).data.numpy() > 0.5).astype("int") == Y.numpy()).mean()

0.8514548238897397